[package]
name = "bridge-supported-chains"
description = "bridge components for the supported networks"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

version = { workspace = true }

[lib]
path = "src/lib.rs"

[dependencies]
aptos-sdk.workspace = true
aptos-types.workspace = true
bcs = { workspace = true }
async-trait = { workspace = true }
anyhow = { workspace = true }
derive-new = { workspace = true }
futures = { workspace = true }
dashmap = { workspace = true }
poem = { workspace = true }
hex = { workspace = true }
keccak-hash = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rand_chacha = "0.2.2"
rand = { workspace = true }
thiserror = { workspace = true }

alloy = { workspace = true, features = [
  "full",
  "rpc",
  "rpc-types",
  "serde",
  "rlp",
  "contract",
  "sol-types",
] }
alloy-rlp.workspace = true

dot-movement = { workspace = true }
suzuka-config = { workspace = true }
bridge-shared = { workspace = true }
serde_with = { workspace = true }
url = { workspace = true, features = ["serde"] }

#To be removed after send_transaction refactor
mcr-settlement-client = { workspace = true }
